package transfer

import "github.com/rumanzo/bt2qbt/pkg/delugeStructures"

func BuildDelugeFastresume(transfer *TransferStructure) *delugeStructures.DelugeFastresume {
	fast := transfer.Fastresume
	return &delugeStructures.DelugeFastresume{
		ActiveTime:         fast.ActiveTime,
		AddedTime:          fast.AddedTime,
		Allocation:         fast.Allocation,
		ApplyIpFilter:      fast.ApplyIpFilter,
		AutoManaged:        fast.AutoManaged,
		BannedPeers:        fast.BannedPeers,
		BannedPeers6:       fast.BannedPeers6,
		CompletedTime:      fast.CompletedTime,
		DisableDht:         fast.DisableDht,
		DisableLsd:         fast.DisableLsd,
		DisablePex:         fast.DisablePex,
		DownloadRateLimit:  fast.DownloadRateLimit,
		FileFormat:         fast.FileFormat,
		FilePriority:       fast.FilePriority,
		FileVersion:        fast.FileVersion,
		FinishedTime:       fast.FinishedTime,
		HttpSeeds:          fast.HttpSeeds,
		Info:               fast.Info,
		InfoHash:           fast.InfoHash,
		InfoHash2:          fast.InfoHash2,
		LastDownload:       fast.LastDownload,
		LastSeenComplete:   fast.LastSeenComplete,
		LastUpload:         fast.LastUpload,
		LibTorrentVersion:  "1.2.19.0",
		MappedFiles:        fast.MappedFiles,
		MaxConnections:     fast.MaxConnections,
		MaxUploads:         fast.MaxUploads,
		Name:               fast.Name,
		NumComplete:        fast.NumComplete,
		NumDownloaded:      fast.NumDownloaded,
		NumIncomplete:      fast.NumIncomplete,
		Paused:             fast.Paused,
		Peers:              fast.Peers,
		Peers6:             fast.Peers6,
		Pieces:             fast.Pieces,
		SavePath:           fast.SavePath,
		SeedMode:           fast.SeedMode,
		SeedingTime:        fast.SeedingTime,
		SequentialDownload: fast.SequentialDownload,
		ShareMode:          fast.ShareMode,
		StopWhenReady:      fast.StopWhenReady,
		SuperSeeding:       fast.SuperSeeding,
		TotalDownloaded:    fast.TotalDownloaded,
		TotalUploaded:      fast.TotalUploaded,
		Trackers:           fast.Trackers,
		Unfinished:         fast.Unfinished,
		UploadMode:         fast.UploadMode,
		UploadRateLimit:    fast.UploadRateLimit,
		UrlList:            fast.UrlList,
	}
}
